name: term-cheat
version: git
summary: Collect and find termial commands.
description: |
  TermCheat is a searchable library of commands that you can copy remix and extend.
grade: devel
confinement: classic
base: core18
parts:
  term-cheat:
    plugin: python
    python-version: python3
    source: .
    source-type: git
  python-wrapper:
    plugin: dump
    source: bin
    stage:
      - term-cheat-app
    prime:
      - term-cheat-app
apps:
  term-cheat:
    command: term-cheat-app
